# Generated by Django 3.2.4 on 2021-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210706_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_or_dislike',
            field=models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7),
        ),
    ]
