# Generated by Django 3.2.4 on 2021-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.AlterField(
            model_name='topic',
            name='additional_info',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
