# Generated by Django 3.2.4 on 2021-07-13 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_cars_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=30, verbose_name='Кузов')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=50, verbose_name='Название авто')),
                ('text', models.TextField(verbose_name='Описание')),
                ('engine_volume', models.FloatField(verbose_name='Обьем двигателя (л)')),
                ('power', models.IntegerField(verbose_name='Мощность (л.с)')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км)')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('city', models.CharField(max_length=20, verbose_name='Местонахождение/город')),
                ('prise', models.FloatField(verbose_name='Цена (BYN)')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('photo1', models.ImageField(upload_to='used_cars')),
                ('photo2', models.ImageField(upload_to='used_cars')),
                ('photo3', models.ImageField(upload_to='used_cars')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_body', verbose_name='Кузов')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=30, verbose_name='Тип топлива')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=30, verbose_name='Коробка')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_type_of_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_drive', models.CharField(max_length=30, verbose_name='Привод')),
            ],
        ),
        migrations.CreateModel(
            name='Used_cars_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='Продукты', to='used_cars.Used_cars_cars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='used_cars_cars',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='used_cars_cars',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_fuel', verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='used_cars_cars',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_status', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='used_cars_cars',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_transmission', verbose_name='Коробка'),
        ),
        migrations.AddField(
            model_name='used_cars_cars',
            name='type_of_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_cars.used_cars_type_of_drive', verbose_name='Привод'),
        ),
    ]
