# Generated by Django 3.2.4 on 2021-07-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='стоимость квартиры')),
                ('cost_dollar', models.FloatField(default=2.5743, verbose_name='курс доллара')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='этаж')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая площадь')),
                ('living_space', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='жилая площадь')),
                ('kitchen_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='площадь кухни')),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='высота потолка')),
                ('number_of_rooms', models.PositiveIntegerField(default=1, verbose_name='количество комнат')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(verbose_name='описание')),
                ('telephone', models.CharField(max_length=25, verbose_name='номер телефона')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
                ('flat_or_apartment', models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом')], max_length=35, verbose_name='дом или квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='стоимость квартиры')),
                ('cost_dollar', models.FloatField(default=2.5743, verbose_name='курс доллара')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='этаж')),
                ('number_of_rooms', models.PositiveIntegerField(default=1, verbose_name='количество комнат')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(verbose_name='описание')),
                ('telephone', models.CharField(max_length=25, verbose_name='номер телефона')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
                ('tv', models.BooleanField(default=False, verbose_name='телевизор')),
                ('furniture', models.BooleanField(default=False, verbose_name='мебель')),
                ('plate', models.BooleanField(default=False, verbose_name='плита')),
                ('refrigerator', models.BooleanField(default=False, verbose_name='холодильник')),
                ('internet', models.BooleanField(default=False, verbose_name='интернет')),
                ('conditioning', models.BooleanField(default=False, verbose_name='кондиционер')),
                ('washer', models.BooleanField(default=False, verbose_name='стиральная машина')),
                ('flat_or_apartment', models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом')], max_length=35, verbose_name='дом или квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_rent', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_rent', to='houses_and_apartments.rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
                ('saleflat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='houses_and_apartments.saleflat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
