# Generated by Django 3.2.4 on 2021-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses_and_apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost_dollar',
            field=models.FloatField(default=2.5663, verbose_name='курс доллара'),
        ),
        migrations.AlterField(
            model_name='saleflat',
            name='cost_dollar',
            field=models.FloatField(default=2.5663, verbose_name='курс доллара'),
        ),
    ]
